import type { ToolDefinition } from './types'

export type WhmLayout = 'form' | 'wizard' | 'table' | 'confirm' | 'status' | 'restart' | 'account-action' | 'settings'

export interface WhmField {
	name: string
	label: string
	type: 'text' | 'password' | 'number' | 'select' | 'textarea' | 'checkbox' | 'account' | 'package'
	options?: Array<{ value: string; label: string }>
	required?: boolean
	help?: string
	defaultValue?: string
}

export interface WhmFeature {
	id: string
	label: string
	description: string
	category: string
	icon: string
	layout: WhmLayout
	path: string
	capabilities: string[]
	matchAll?: boolean
	dedicated?: boolean
	steps: string[]
	fields?: WhmField[]
	settingKey?: string
	related?: string[]
	accountAction?: 'patch' | 'suspend' | 'unsuspend' | 'password' | 'terminate' | 'impersonate' | 'service-restart'
}

function feature (entry: WhmFeature): WhmFeature {
	return entry
}

const accountSelect: WhmField = { name: 'account_id', label: 'Account', type: 'account', required: true }
const packageSelect: WhmField = { name: 'package_id', label: 'Package', type: 'package', required: true }

export const whmFeatures: WhmFeature[] = [
	feature({ id: 'home', label: 'Home', description: 'Host overview, favorites, status, and every administration tool grouped like WHM.', category: 'Kelmor Director', icon: 'home', layout: 'status', path: '/', capabilities: ['server.read', 'accounts.read'], dedicated: true, steps: ['Review host health', 'Open a tool'] }),

	feature({ id: 'create-account', label: 'Create a New Account', description: 'Provision a hosting account with identity, package, ownership, and reviewed payload.', category: 'Account Functions', icon: 'plus', layout: 'wizard', path: '/accounts/create', capabilities: ['accounts.create', 'packages.read'], matchAll: true, dedicated: true, steps: ['Identity', 'Package', 'Review', 'Queue provision'], related: ['packages', 'list-accounts'] }),
	feature({ id: 'change-site-ip', label: "Change Site's IP Address", description: 'Assign a dedicated or shared IP to an existing account and queue reconcile.', category: 'Account Functions', icon: 'globe', layout: 'account-action', path: '/tools/change-site-ip', capabilities: ['accounts.modify'], accountAction: 'patch', steps: ['Select account', 'Enter IP', 'Review', 'Queue change'], fields: [accountSelect, { name: 'ip_address', label: 'IP address', type: 'text', required: true, help: 'Leave blank on save to return the account to the shared address.' }], related: ['list-accounts', 'rebuild-ip-pool'] }),
	feature({ id: 'email-all-users', label: 'Email All Users', description: 'Compose a message to every account owner. The draft is stored with the host settings and can be copied into your mail relay.', category: 'Account Functions', icon: 'mail', layout: 'settings', path: '/tools/email-all-users', capabilities: ['accounts.read'], settingKey: 'email_all_users', steps: ['Write message', 'Review recipients', 'Save draft'], fields: [{ name: 'subject', label: 'Subject', type: 'text', required: true }, { name: 'body', label: 'Message', type: 'textarea', required: true }, { name: 'from', label: 'From address', type: 'text', required: true }], related: ['contact-manager'] }),
	feature({ id: 'force-password', label: 'Force Password Change', description: 'Rotate owner credentials and optionally require another change at next Control sign-in.', category: 'Account Functions', icon: 'key', layout: 'account-action', path: '/accounts?task=password', capabilities: ['accounts.read', 'accounts.modify'], matchAll: true, dedicated: true, accountAction: 'password', steps: ['Select account', 'Set password', 'Queue rotation'] }),
	feature({ id: 'limit-bandwidth', label: 'Limit Bandwidth Usage', description: 'Override the monthly bandwidth allotment for one account without editing the package.', category: 'Account Functions', icon: 'meter', layout: 'account-action', path: '/tools/limit-bandwidth', capabilities: ['accounts.modify'], accountAction: 'patch', settingKey: 'bandwidth_overrides', steps: ['Select account', 'Set monthly bytes', 'Review', 'Save override'], fields: [accountSelect, { name: 'bandwidth_bytes_monthly', label: 'Monthly bandwidth bytes', type: 'number', required: true, defaultValue: '107374182400' }], related: ['reset-bandwidth', 'usage'] }),
	feature({ id: 'suspend-account', label: 'Manage Account Suspension', description: 'Suspend or unsuspend an account and queue Linux, vhost, cron, and mail lockout.', category: 'Account Functions', icon: 'pause', layout: 'account-action', path: '/accounts?task=suspension', capabilities: ['accounts.read', 'accounts.suspend'], matchAll: true, dedicated: true, accountAction: 'suspend', steps: ['Select account', 'Confirm impact', 'Queue'] }),
	feature({ id: 'manage-demo-mode', label: 'Manage Demo Mode', description: 'Mark accounts as demonstration tenants. Demo accounts keep services but block destructive owner writes.', category: 'Account Functions', icon: 'edit', layout: 'settings', path: '/tools/manage-demo-mode', capabilities: ['accounts.modify'], settingKey: 'demo_accounts', steps: ['Select accounts', 'Save demo set'], fields: [{ name: 'usernames', label: 'Demo usernames (comma separated)', type: 'textarea', help: 'These accounts stay provisioned for sales demonstrations.' }], related: ['list-accounts'] }),
	feature({ id: 'manage-shell', label: 'Manage Shell Access', description: 'Set the POSIX shell class for an account: sftp-only, jailed, or nologin.', category: 'Account Functions', icon: 'key', layout: 'account-action', path: '/tools/manage-shell', capabilities: ['accounts.modify'], accountAction: 'patch', steps: ['Select account', 'Choose shell', 'Review', 'Queue reconcile'], fields: [accountSelect, { name: 'shell_class', label: 'Shell class', type: 'select', required: true, options: [{ value: 'sftp-only', label: 'SFTP only' }, { value: 'nologin', label: 'No login' }, { value: 'jailed', label: 'Jailed shell' }] }], related: ['list-accounts'] }),
	feature({ id: 'modify-account', label: 'Modify an Account', description: 'Change domain, IP, package, reseller ownership, and login access.', category: 'Account Functions', icon: 'edit', layout: 'account-action', path: '/accounts?task=modify', capabilities: ['accounts.read', 'accounts.modify'], matchAll: true, dedicated: true, accountAction: 'patch', steps: ['Select account', 'Edit assignment', 'Review'] }),
	feature({ id: 'password-modification', label: 'Password Modification', description: 'Set a new owner password for an account without requiring a second change.', category: 'Account Functions', icon: 'key', layout: 'account-action', path: '/accounts?task=password', capabilities: ['accounts.modify'], dedicated: true, accountAction: 'password', steps: ['Select account', 'Set password'] }),
	feature({ id: 'quota-modification', label: 'Quota Modification', description: 'Override disk quota for one account. The agent enforces the cap even without kernel usrquota.', category: 'Account Functions', icon: 'meter', layout: 'account-action', path: '/tools/quota-modification', capabilities: ['accounts.modify'], settingKey: 'quota_overrides', steps: ['Select account', 'Set disk bytes', 'Save override'], fields: [accountSelect, { name: 'disk_bytes', label: 'Disk bytes', type: 'number', required: true, defaultValue: '10737418240' }], related: ['usage', 'packages'] }),
	feature({ id: 'raw-nginx-log', label: 'Raw NGINX Log Download', description: 'Locate and copy the nginx access/error log paths for an account vhost.', category: 'Account Functions', icon: 'files', layout: 'account-action', path: '/tools/raw-nginx-log', capabilities: ['accounts.read'], steps: ['Select account', 'Copy log paths'], fields: [accountSelect], related: ['file-manager'] }),
	feature({ id: 'rearrange-account', label: 'Rearrange an Account', description: 'Review the home directory that stores an account. Kelmor homes stay under /home/<user>.', category: 'Account Functions', icon: 'files', layout: 'account-action', path: '/tools/rearrange-account', capabilities: ['accounts.read'], steps: ['Select account', 'Review home path'], fields: [accountSelect], related: ['list-accounts'] }),
	feature({ id: 'reset-bandwidth', label: 'Reset Account Bandwidth Limit', description: 'Clear a per-account bandwidth override so the package quota applies again.', category: 'Account Functions', icon: 'meter', layout: 'account-action', path: '/tools/reset-bandwidth', capabilities: ['accounts.modify'], settingKey: 'bandwidth_overrides', steps: ['Select account', 'Clear override'], fields: [accountSelect], related: ['limit-bandwidth'] }),
	feature({ id: 'skeleton-directory', label: 'Skeleton Directory', description: 'Show the skeleton copied into new account homes during provision.', category: 'Account Functions', icon: 'files', layout: 'status', path: '/tools/skeleton-directory', capabilities: ['accounts.create'], steps: ['Review skeleton path'], related: ['create-account'] }),
	feature({ id: 'terminate-account', label: 'Terminate Accounts', description: 'Permanently remove an account after typed confirmation.', category: 'Account Functions', icon: 'trash', layout: 'account-action', path: '/accounts?task=terminate', capabilities: ['accounts.read', 'accounts.terminate'], matchAll: true, dedicated: true, accountAction: 'terminate', steps: ['Select account', 'Type username', 'Terminate'] }),
	feature({ id: 'unsuspend-bandwidth', label: 'Unsuspend Bandwidth Exceeders', description: 'Unsuspend every account currently suspended for bandwidth.', category: 'Account Functions', icon: 'pause', layout: 'confirm', path: '/tools/unsuspend-bandwidth', capabilities: ['accounts.suspend'], steps: ['Review exceeders', 'Confirm bulk unsuspend'], related: ['over-quota', 'suspend-account'] }),
	feature({ id: 'change-package', label: 'Upgrade/Downgrade an Account', description: 'Move an account to a different resource package.', category: 'Account Functions', icon: 'box', layout: 'account-action', path: '/accounts?task=package', capabilities: ['accounts.read', 'accounts.modify'], matchAll: true, dedicated: true, accountAction: 'patch', steps: ['Select account', 'Choose package', 'Review'] }),
	feature({ id: 'login-control', label: 'Login to Kelmor Control', description: 'Open an audited Control session as the account owner.', category: 'Account Functions', icon: 'key', layout: 'account-action', path: '/accounts?task=login', capabilities: ['accounts.read', 'accounts.impersonate'], matchAll: true, dedicated: true, accountAction: 'impersonate', steps: ['Select account', 'Enter reason', 'Open Control'] }),
	feature({ id: 'cron-jobs', label: 'Cron Jobs', description: 'Create and remove account-scoped scheduled tasks.', category: 'Account Functions', icon: 'jobs', layout: 'table', path: '/cron', capabilities: ['accounts.read', 'cron.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Add or delete tasks'] }),

	feature({ id: 'list-accounts', label: 'List Accounts', description: 'Search, sort, suspend, and manage POSIX hosting tenants.', category: 'Account Information', icon: 'users', layout: 'table', path: '/accounts', capabilities: ['accounts.read'], dedicated: true, steps: ['Search', 'Select', 'Act'] }),
	feature({ id: 'account-summary', label: 'Account Summary', description: 'Open an account hub for status, usage, isolation, and linked services.', category: 'Account Information', icon: 'account', layout: 'status', path: '/accounts?task=summary', capabilities: ['accounts.read'], dedicated: true, steps: ['Select account', 'Review'] }),
	feature({ id: 'list-domains', label: 'List Domains', description: 'Inventory addon, subdomain, and parked domains.', category: 'Account Information', icon: 'globe', layout: 'table', path: '/domains', capabilities: ['accounts.read', 'domains.read'], matchAll: true, dedicated: true, steps: ['Filter type', 'Add or delete'] }),
	feature({ id: 'list-subdomains', label: 'List Subdomains', description: 'Filter the domain inventory to subdomains.', category: 'Account Information', icon: 'globe', layout: 'table', path: '/domains?view=subdomain', capabilities: ['accounts.read', 'domains.read'], matchAll: true, dedicated: true, steps: ['Review subdomains'] }),
	feature({ id: 'list-parked', label: 'List Parked Domains', description: 'Filter the domain inventory to parked alias domains.', category: 'Account Information', icon: 'globe', layout: 'table', path: '/domains?view=alias', capabilities: ['accounts.read', 'domains.read'], matchAll: true, dedicated: true, steps: ['Review parked domains'] }),
	feature({ id: 'suspended', label: 'List Suspended Accounts', description: 'Review suspended hosting identities.', category: 'Account Information', icon: 'pause', layout: 'table', path: '/accounts?view=suspended', capabilities: ['accounts.read'], dedicated: true, steps: ['Review', 'Unsuspend'] }),
	feature({ id: 'over-quota', label: 'Show Accounts Over Quota', description: 'Find accounts over package disk or bandwidth quota.', category: 'Account Information', icon: 'meter', layout: 'table', path: '/accounts?view=over-quota', capabilities: ['accounts.read', 'billing.usage.read', 'packages.read'], matchAll: true, dedicated: true, steps: ['Review usage'] }),
	feature({ id: 'usage', label: 'View Bandwidth Usage', description: 'Compare disk, bandwidth, process, and memory usage.', category: 'Account Information', icon: 'chart', layout: 'table', path: '/usage', capabilities: ['billing.usage.read', 'accounts.read', 'packages.read'], matchAll: true, dedicated: true, steps: ['Compare accounts'] }),

	feature({ id: 'backup-config', label: 'Backup Configuration', description: 'Set default backup destination, retention, and encryption policy for new account backups.', category: 'Backup', icon: 'transfer', layout: 'settings', path: '/tools/backup-config', capabilities: ['backups.create'], settingKey: 'backup_configuration', steps: ['Choose destination', 'Set retention', 'Save'], fields: [{ name: 'destination', label: 'Default destination', type: 'select', options: [{ value: 'local', label: 'Local' }, { value: 'sftp', label: 'SFTP' }, { value: 's3', label: 'S3' }], defaultValue: 'local' }, { name: 'retention_days', label: 'Retention days', type: 'number', defaultValue: '14' }, { name: 'encrypt', label: 'Encrypt archives (HPM1)', type: 'checkbox', defaultValue: 'on' }], related: ['transfers'] }),
	feature({ id: 'backup-restoration', label: 'Backup Restoration', description: 'Restore an encrypted account archive after reviewing scope.', category: 'Backup', icon: 'transfer', layout: 'table', path: '/transfers', capabilities: ['accounts.read'], dedicated: true, steps: ['Select account', 'Review archive', 'Queue restore'] }),
	feature({ id: 'backup-user-selection', label: 'Backup User Selection', description: 'Choose which accounts are included in scheduled backups.', category: 'Backup', icon: 'transfer', layout: 'settings', path: '/tools/backup-user-selection', capabilities: ['backups.create'], settingKey: 'backup_users', steps: ['Select accounts', 'Save'], fields: [{ name: 'usernames', label: 'Included usernames (comma separated)', type: 'textarea' }], related: ['backup-config'] }),
	feature({ id: 'file-dir-restore', label: 'File and Directory Restoration', description: 'Restore a home-tree path from an HPM1 backup without a full account restore.', category: 'Backup', icon: 'files', layout: 'account-action', path: '/tools/file-dir-restore', capabilities: ['backups.restore'], steps: ['Select account', 'Enter path', 'Queue restore'], fields: [accountSelect, { name: 'path', label: 'Path under home', type: 'text', required: true, defaultValue: 'public_html' }], related: ['transfers', 'file-manager'] }),
	feature({ id: 'transfers', label: 'Transfer or Restore an Account', description: 'Native export/import, extracted archive import, account copy, and restore.', category: 'Transfers', icon: 'transfer', layout: 'wizard', path: '/transfers', capabilities: ['accounts.read'], dedicated: true, steps: ['Choose journey', 'Review', 'Queue'] }),

	feature({ id: 'configuration-cluster', label: 'Configuration Cluster', description: 'Link this Kelmor node to peer Directors that should share packages and feature sets.', category: 'Clusters', icon: 'globe', layout: 'settings', path: '/tools/configuration-cluster', capabilities: ['server.settings.write'], settingKey: 'configuration_cluster', steps: ['Add peer URL', 'Save'], fields: [{ name: 'peers', label: 'Peer Director URLs', type: 'textarea', help: 'One URL per line.' }] }),
	feature({ id: 'dns-cluster', label: 'DNS Cluster', description: 'Separate authoritative nameservers from this hosting node.', category: 'Clusters', icon: 'globe', layout: 'settings', path: '/tools/dns-cluster', capabilities: ['dns.write'], settingKey: 'dns_cluster', steps: ['Enter nameservers', 'Save'], fields: [{ name: 'nameservers', label: 'Cluster nameservers', type: 'textarea', help: 'One hostname per line.' }], related: ['dns'] }),
	feature({ id: 'remote-access-key', label: 'Remote Access Key', description: 'Issue and store a Director-to-Director remote access token.', category: 'Clusters', icon: 'key', layout: 'settings', path: '/tools/remote-access-key', capabilities: ['api_tokens.write'], settingKey: 'remote_access_key', steps: ['Name the key', 'Save'], fields: [{ name: 'name', label: 'Key name', type: 'text', required: true }] }),

	feature({ id: 'dns', label: 'DNS Zone Manager', description: 'Edit zones, records, and DNSSEC for an account.', category: 'DNS Functions', icon: 'globe', layout: 'table', path: '/dns', capabilities: ['accounts.read', 'dns.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Edit records'] }),
	feature({ id: 'add-dns-zone', label: 'Add a DNS Zone', description: 'Create a managed DNS zone by adding a domain to an account.', category: 'DNS Functions', icon: 'plus', layout: 'account-action', path: '/domains', capabilities: ['domains.write'], dedicated: true, steps: ['Select account', 'Add domain'] }),
	feature({ id: 'add-hostname-a', label: 'Add an A Entry for Your Hostname', description: 'Publish an A record for the panel hostname in the host DNS zone.', category: 'DNS Functions', icon: 'globe', layout: 'settings', path: '/tools/add-hostname-a', capabilities: ['dns.write'], settingKey: 'hostname_a', steps: ['Confirm hostname', 'Save A target'], fields: [{ name: 'address', label: 'IPv4 address', type: 'text', required: true }], related: ['change-hostname'] }),
	feature({ id: 'delete-dns-zone', label: 'Delete a DNS Zone', description: 'Remove a non-primary domain and its zone after confirmation.', category: 'DNS Functions', icon: 'trash', layout: 'table', path: '/domains', capabilities: ['domains.write'], dedicated: true, steps: ['Select domain', 'Delete'] }),
	feature({ id: 'edit-zone-templates', label: 'Edit Zone Templates', description: 'Default TTL, SOA, and record templates applied to new zones.', category: 'DNS Functions', icon: 'edit', layout: 'settings', path: '/tools/edit-zone-templates', capabilities: ['dns.write'], settingKey: 'zone_templates', steps: ['Edit template', 'Save'], fields: [{ name: 'ttl', label: 'Default TTL', type: 'number', defaultValue: '3600' }, { name: 'soa_email', label: 'SOA email', type: 'text' }, { name: 'extra_records', label: 'Extra records (one BIND line each)', type: 'textarea' }] }),
	feature({ id: 'email-routing-dns', label: 'Email Routing Configuration', description: 'Set catch-all routing for mail domains.', category: 'DNS Functions', icon: 'mail', layout: 'table', path: '/email?tab=domains', capabilities: ['mail.write'], dedicated: true, steps: ['Select domain', 'Set policy'] }),
	feature({ id: 'dkim-spf-global', label: 'Enable DKIM/SPF Globally', description: 'Require DKIM and SPF records on every mail domain.', category: 'DNS Functions', icon: 'mail', layout: 'settings', path: '/tools/dkim-spf-global', capabilities: ['dns.write'], settingKey: 'dkim_spf_global', steps: ['Enable policy', 'Save'], fields: [{ name: 'require_spf', label: 'Require SPF', type: 'checkbox', defaultValue: 'on' }, { name: 'require_dkim', label: 'Require DKIM', type: 'checkbox', defaultValue: 'on' }, { name: 'require_dmarc', label: 'Require DMARC', type: 'checkbox', defaultValue: 'on' }], related: ['deliverability'] }),
	feature({ id: 'dns-cleanup', label: 'Perform a DNS Cleanup', description: 'Remove leftover records for terminated accounts. Review before applying.', category: 'DNS Functions', icon: 'globe', layout: 'confirm', path: '/tools/dns-cleanup', capabilities: ['dns.write'], steps: ['Review leftover zones', 'Confirm cleanup'] }),
	feature({ id: 'set-zone-ttl', label: 'Set Zone TTL', description: 'Default TTL written into new and updated records.', category: 'DNS Functions', icon: 'globe', layout: 'settings', path: '/tools/set-zone-ttl', capabilities: ['dns.write'], settingKey: 'zone_ttl', steps: ['Set TTL', 'Save'], fields: [{ name: 'ttl', label: 'TTL seconds', type: 'number', defaultValue: '3600', required: true }] }),
	feature({ id: 'domain-forwarding', label: 'Setup/Edit Domain Forwarding', description: 'Forward an alias/parked domain to another URL.', category: 'DNS Functions', icon: 'globe', layout: 'account-action', path: '/tools/domain-forwarding', capabilities: ['domains.write'], settingKey: 'domain_forwards', steps: ['Select account', 'Set target', 'Save'], fields: [accountSelect, { name: 'source', label: 'Source domain', type: 'text', required: true }, { name: 'target', label: 'Target URL', type: 'text', required: true }] }),

	feature({ id: 'email', label: 'Email Management', description: 'Mail domains, mailboxes, aliases, mailing lists, and routing.', category: 'Email', icon: 'mail', layout: 'table', path: '/email', capabilities: ['accounts.read', 'mail.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Manage mail'] }),
	feature({ id: 'deliverability', label: 'Email Deliverability', description: 'Inspect SPF, DKIM, and DMARC records.', category: 'Email', icon: 'mail', layout: 'table', path: '/deliverability', capabilities: ['accounts.read', 'mail.read', 'dns.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Review checks'] }),
	feature({ id: 'webmail', label: 'Webmail', description: 'Launch webmail and copy IMAP/SMTP settings.', category: 'Email', icon: 'webmail', layout: 'status', path: '/webmail', capabilities: ['accounts.read', 'mail.read'], matchAll: true, dedicated: true, steps: ['Select mailbox', 'Open'] }),
	feature({ id: 'filter-country', label: 'Filter Incoming Emails by Country', description: 'Reject or greylist mail from selected country codes.', category: 'Email', icon: 'mail', layout: 'settings', path: '/tools/filter-country', capabilities: ['mail.write'], settingKey: 'mail_country_filter', steps: ['Enter country codes', 'Save'], fields: [{ name: 'action', label: 'Action', type: 'select', options: [{ value: 'reject', label: 'Reject' }, { value: 'greylist', label: 'Greylist' }], defaultValue: 'reject' }, { name: 'countries', label: 'ISO country codes', type: 'textarea' }] }),
	feature({ id: 'filter-domain', label: 'Filter Incoming Emails by Domain', description: 'Block or allow listed sending domains.', category: 'Email', icon: 'mail', layout: 'settings', path: '/tools/filter-domain', capabilities: ['mail.write'], settingKey: 'mail_domain_filter', steps: ['Edit lists', 'Save'], fields: [{ name: 'deny', label: 'Denied domains', type: 'textarea' }, { name: 'allow', label: 'Allowed domains', type: 'textarea' }] }),
	feature({ id: 'greylisting', label: 'Greylisting', description: 'Temporarily defer unknown senders to reduce spam.', category: 'Email', icon: 'mail', layout: 'settings', path: '/tools/greylisting', capabilities: ['mail.write'], settingKey: 'greylisting', steps: ['Enable', 'Save'], fields: [{ name: 'enabled', label: 'Enable greylisting', type: 'checkbox' }, { name: 'delay_minutes', label: 'Defer minutes', type: 'number', defaultValue: '5' }] }),
	feature({ id: 'mail-queue', label: 'Mail Queue Manager', description: 'Show and flush the live Postfix queue through audited host recipes.', category: 'Email', icon: 'mail', layout: 'status', path: '/tools/mail-queue', capabilities: ['mail.write'], steps: ['Review the queue', 'Flush deferred mail'], related: ['jobs'] }),
	feature({ id: 'mail-delivery-reports', label: 'Mail Delivery Reports', description: 'Filter recent mail jobs and audit events for delivery failures.', category: 'Email', icon: 'mail', layout: 'table', path: '/jobs?q=mail', capabilities: ['accounts.read'], dedicated: true, steps: ['Filter mail jobs'] }),
	feature({ id: 'spamd-startup', label: 'Spamd Startup Configuration', description: 'Configure rspamd/spamd startup and scoring thresholds.', category: 'Email', icon: 'mail', layout: 'settings', path: '/tools/spamd-startup', capabilities: ['server.settings.write'], settingKey: 'spamd', steps: ['Set thresholds', 'Save'], fields: [{ name: 'enabled', label: 'Enable spam filtering', type: 'checkbox', defaultValue: 'on' }, { name: 'reject_score', label: 'Reject score', type: 'number', defaultValue: '15' }] }),
	feature({ id: 'repair-mailbox-perms', label: 'Repair Mailbox Permissions', description: 'Queue a mail.maps reconcile so Maildir ownership matches the POSIX tenant.', category: 'Email', icon: 'mail', layout: 'account-action', path: '/tools/repair-mailbox-perms', capabilities: ['mail.write'], steps: ['Select account', 'Queue repair'], fields: [accountSelect] }),

	feature({ id: 'add-ip', label: 'Add a New IP Address', description: 'Register an additional address the host may assign to accounts.', category: 'IP Functions', icon: 'globe', layout: 'settings', path: '/tools/add-ip', capabilities: ['server.settings.write'], settingKey: 'ip_pool', steps: ['Enter address', 'Save'], fields: [{ name: 'address', label: 'IP address', type: 'text', required: true }, { name: 'device', label: 'Ethernet device', type: 'text', defaultValue: 'eth0' }] }),
	feature({ id: 'assign-ipv6', label: 'Assign IPv6 Address', description: 'Assign an IPv6 address from a configured range to an account.', category: 'IP Functions', icon: 'globe', layout: 'account-action', path: '/tools/assign-ipv6', capabilities: ['accounts.modify'], accountAction: 'patch', steps: ['Select account', 'Enter IPv6', 'Save'], fields: [accountSelect, { name: 'ip_address', label: 'IPv6 address', type: 'text', required: true }] }),
	feature({ id: 'remote-service-ips', label: 'Configure Remote Service IPs', description: 'IPs used for remote MySQL, DNS, or mail services.', category: 'IP Functions', icon: 'globe', layout: 'settings', path: '/tools/remote-service-ips', capabilities: ['server.settings.write'], settingKey: 'remote_service_ips', steps: ['Enter IPs', 'Save'], fields: [{ name: 'mysql', label: 'Remote SQL IP', type: 'text' }, { name: 'dns', label: 'Remote DNS IP', type: 'text' }, { name: 'mail', label: 'Remote mail IP', type: 'text' }] }),
	feature({ id: 'ip-migration', label: 'IP Migration Wizard', description: 'Move accounts from one address to another in a reviewed wizard.', category: 'IP Functions', icon: 'globe', layout: 'wizard', path: '/tools/ip-migration', capabilities: ['accounts.modify'], steps: ['Source IP', 'Destination IP', 'Review accounts', 'Queue'], fields: [{ name: 'from_ip', label: 'Source IP', type: 'text', required: true }, { name: 'to_ip', label: 'Destination IP', type: 'text', required: true }] }),
	feature({ id: 'ipv6-ranges', label: 'IPv6 Address Ranges', description: 'Define IPv6 ranges available for assignment.', category: 'IP Functions', icon: 'globe', layout: 'settings', path: '/tools/ipv6-ranges', capabilities: ['server.settings.write'], settingKey: 'ipv6_ranges', steps: ['Enter CIDR', 'Save'], fields: [{ name: 'ranges', label: 'CIDR ranges', type: 'textarea' }] }),
	feature({ id: 'rebuild-ip-pool', label: 'Rebuild the IP Address Pool', description: 'Rebuild the assignable IPv4 pool from configured addresses.', category: 'IP Functions', icon: 'globe', layout: 'confirm', path: '/tools/rebuild-ip-pool', capabilities: ['server.settings.write'], steps: ['Review pool', 'Rebuild'] }),
	feature({ id: 'show-ip-usage', label: 'Show IP Address Usage', description: 'List accounts and the IPs they currently use.', category: 'IP Functions', icon: 'globe', layout: 'table', path: '/accounts', capabilities: ['accounts.read'], dedicated: true, steps: ['Review inventory'] }),

	feature({ id: 'change-hostname', label: 'Change Hostname', description: 'Set the public hostname used on the Director chrome and mail myhostname.', category: 'Networking Setup', icon: 'globe', layout: 'settings', path: '/tools/change-hostname', capabilities: ['server.settings.write'], settingKey: 'hostname', steps: ['Enter FQDN', 'Review', 'Save'], fields: [{ name: 'hostname', label: 'Hostname', type: 'text', required: true, help: 'Must be a resolvable FQDN.' }], related: ['basic-setup'] }),
	feature({ id: 'resolver-config', label: 'Resolver Configuration', description: 'Configure the recursive resolvers this host uses.', category: 'Networking Setup', icon: 'globe', layout: 'settings', path: '/tools/resolver-config', capabilities: ['server.settings.write'], settingKey: 'resolvers', steps: ['Enter resolvers', 'Save'], fields: [{ name: 'nameservers', label: 'Resolver IPs', type: 'textarea', defaultValue: '1.1.1.1\n8.8.8.8' }] }),

	feature({ id: 'packages', label: 'Edit a Package', description: 'Create, edit, and safely delete resource packages.', category: 'Packages', icon: 'box', layout: 'table', path: '/packages', capabilities: ['packages.read'], dedicated: true, steps: ['Edit limits', 'Save'] }),
	feature({ id: 'add-package', label: 'Add a Package', description: 'Define a new reusable account limit set.', category: 'Packages', icon: 'plus', layout: 'table', path: '/packages', capabilities: ['packages.write'], dedicated: true, steps: ['Fill limits', 'Save'] }),
	feature({ id: 'delete-package', label: 'Delete a Package', description: 'Remove a package that no account references.', category: 'Packages', icon: 'trash', layout: 'table', path: '/packages', capabilities: ['packages.write'], dedicated: true, steps: ['Confirm name'] }),
	feature({ id: 'features', label: 'Feature Manager', description: 'Review feature sets and assigned packages.', category: 'Packages', icon: 'box', layout: 'table', path: '/features', capabilities: ['packages.read'], dedicated: true, steps: ['Inspect set', 'Assign on package'] }),

	feature({ id: 'resellers', label: 'Edit Reseller Nameservers and Privileges', description: 'Manage reseller identity, nameservers, and privilege mask.', category: 'Resellers', icon: 'briefcase', layout: 'table', path: '/resellers', capabilities: ['resellers.read'], dedicated: true, steps: ['Edit reseller', 'Save'] }),
	feature({ id: 'change-ownership', label: 'Change Ownership of an Account', description: 'Move an account to another reseller or to direct ownership.', category: 'Resellers', icon: 'briefcase', layout: 'account-action', path: '/accounts?task=modify', capabilities: ['accounts.modify'], dedicated: true, accountAction: 'patch', steps: ['Select account', 'Choose reseller'] }),
	feature({ id: 'change-ownership-bulk', label: 'Change Ownership of Multiple Accounts', description: 'Move several accounts to one reseller in one reviewed action.', category: 'Resellers', icon: 'briefcase', layout: 'settings', path: '/tools/change-ownership-bulk', capabilities: ['accounts.modify'], settingKey: 'bulk_ownership', steps: ['List usernames', 'Choose reseller', 'Save plan'], fields: [{ name: 'usernames', label: 'Usernames', type: 'textarea', required: true }, { name: 'reseller_id', label: 'Reseller ID', type: 'text' }] }),
	feature({ id: 'email-resellers', label: 'Email All Resellers', description: 'Draft a message to every reseller contact.', category: 'Resellers', icon: 'mail', layout: 'settings', path: '/tools/email-resellers', capabilities: ['resellers.read'], settingKey: 'email_resellers', steps: ['Write', 'Save draft'], fields: [{ name: 'subject', label: 'Subject', type: 'text', required: true }, { name: 'body', label: 'Message', type: 'textarea', required: true }] }),
	feature({ id: 'reseller-ip-delegation', label: "Manage Reseller's IP Delegation", description: 'Reserve IPs a reseller may assign.', category: 'Resellers', icon: 'globe', layout: 'settings', path: '/tools/reseller-ip-delegation', capabilities: ['resellers.modify'], settingKey: 'reseller_ips', steps: ['Enter IPs', 'Save'], fields: [{ name: 'reseller_id', label: 'Reseller ID', type: 'text', required: true }, { name: 'addresses', label: 'Delegated IPs', type: 'textarea' }] }),
	feature({ id: 'reseller-shared-ip', label: "Manage Reseller's Shared IP", description: 'Set the shared IP used by a reseller’s accounts.', category: 'Resellers', icon: 'globe', layout: 'settings', path: '/tools/reseller-shared-ip', capabilities: ['resellers.modify'], settingKey: 'reseller_shared_ip', steps: ['Select reseller', 'Save IP'], fields: [{ name: 'reseller_id', label: 'Reseller ID', type: 'text', required: true }, { name: 'ip_address', label: 'Shared IP', type: 'text', required: true }] }),
	feature({ id: 'reseller-usage', label: 'View Reseller Usage and Manage Account Status', description: 'Open reseller records and their assigned accounts.', category: 'Resellers', icon: 'chart', layout: 'table', path: '/resellers', capabilities: ['resellers.read'], dedicated: true, steps: ['Inspect usage'] }),

	feature({ id: 'restart-http', label: 'HTTP Server (nginx)', description: 'Reload or restart nginx after a reviewed confirmation.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-http', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'nginx' }] }),
	feature({ id: 'restart-dns', label: 'DNS Server', description: 'Restart PowerDNS.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-dns', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'pdns' }] }),
	feature({ id: 'restart-imap', label: 'IMAP Server', description: 'Restart Dovecot.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-imap', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'dovecot' }] }),
	feature({ id: 'restart-mail', label: 'Mail Server (Postfix)', description: 'Restart Postfix.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-mail', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'postfix' }] }),
	feature({ id: 'restart-php', label: 'PHP-FPM', description: 'Restart php-fpm.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-php', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'php-fpm' }] }),
	feature({ id: 'restart-mysql', label: 'SQL Server (MariaDB)', description: 'Restart MariaDB.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-mysql', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'mariadb' }] }),
	feature({ id: 'restart-pgsql', label: 'SQL Server (PostgreSQL)', description: 'Restart PostgreSQL.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-pgsql', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'postgresql' }] }),
	feature({ id: 'restart-ssh', label: 'SSH Server (OpenSSH)', description: 'Restart sshd. Active sessions disconnect.', category: 'Restart Services', icon: 'pulse', layout: 'restart', path: '/tools/restart-ssh', capabilities: ['server.services.restart'], accountAction: 'service-restart', steps: ['Review impact', 'Confirm'], fields: [{ name: 'service', label: 'Service', type: 'text', defaultValue: 'sshd' }] }),

	feature({ id: 'mod-userdir', label: 'Apache mod_userdir Tweak', description: 'Disable ~username URL access so sites are only reached by their vhosts.', category: 'Security Center', icon: 'shield', layout: 'settings', path: '/tools/mod-userdir', capabilities: ['server.settings.write'], settingKey: 'mod_userdir', steps: ['Choose policy', 'Save'], fields: [{ name: 'disabled', label: 'Disable userdir URLs', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'compiler-access', label: 'Compiler Access', description: 'Allow or deny compiler binaries for tenants.', category: 'Security Center', icon: 'shield', layout: 'settings', path: '/tools/compiler-access', capabilities: ['server.settings.write'], settingKey: 'compiler_access', steps: ['Choose policy', 'Save'], fields: [{ name: 'allow', label: 'Allow compilers for tenants', type: 'checkbox' }] }),
	feature({ id: 'security-policies', label: 'Configure Security Policies', description: 'Password age, idle timeout, and session policy for Director and Control.', category: 'Security Center', icon: 'shield', layout: 'settings', path: '/tools/security-policies', capabilities: ['server.settings.write'], settingKey: 'security_policies', steps: ['Edit policy', 'Save'], fields: [{ name: 'min_password_length', label: 'Minimum password length', type: 'number', defaultValue: '12' }, { name: 'idle_minutes', label: 'Idle timeout minutes', type: 'number', defaultValue: '30' }, { name: 'require_2fa', label: 'Require two-factor for administrators', type: 'checkbox' }] }),
	feature({ id: 'cphulk', label: 'Brute Force Protection', description: 'Lock out sources after repeated failed Director or Control logins.', category: 'Security Center', icon: 'shield', layout: 'settings', path: '/tools/cphulk', capabilities: ['server.settings.write'], settingKey: 'brute_force', steps: ['Set thresholds', 'Save'], fields: [{ name: 'enabled', label: 'Enable protection', type: 'checkbox', defaultValue: 'on' }, { name: 'max_failures', label: 'Failures before lockout', type: 'number', defaultValue: '5' }, { name: 'window_minutes', label: 'Window minutes', type: 'number', defaultValue: '15' }] }),
	feature({ id: 'host-access', label: 'Host Access Control', description: 'Allow or deny Director access by source IP.', category: 'Security Center', icon: 'shield', layout: 'settings', path: '/tools/host-access', capabilities: ['server.firewall.write'], settingKey: 'host_access', steps: ['Edit lists', 'Save'], fields: [{ name: 'allow', label: 'Allow CIDRs', type: 'textarea', defaultValue: '0.0.0.0/0' }, { name: 'deny', label: 'Deny CIDRs', type: 'textarea' }], related: ['security'] }),
	feature({ id: 'external-auth', label: 'Manage External Authentications', description: 'Configure OIDC/SAML providers for Director operators.', category: 'Security Center', icon: 'key', layout: 'settings', path: '/tools/external-auth', capabilities: ['server.settings.write'], settingKey: 'external_auth', steps: ['Enter issuer', 'Save'], fields: [{ name: 'issuer', label: 'Issuer URL', type: 'text' }, { name: 'client_id', label: 'Client ID', type: 'text' }] }),
	feature({ id: 'password-strength', label: 'Password Strength Configuration', description: 'Minimum complexity for account and mailbox passwords.', category: 'Security Center', icon: 'key', layout: 'settings', path: '/tools/password-strength', capabilities: ['server.settings.write'], settingKey: 'password_strength', steps: ['Set rules', 'Save'], fields: [{ name: 'min_length', label: 'Minimum length', type: 'number', defaultValue: '12' }, { name: 'require_symbol', label: 'Require a symbol', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'security-advisor', label: 'Security Advisor', description: 'Review host hardening checks and open the matching tool.', category: 'Security Center', icon: 'audit', layout: 'status', path: '/security', capabilities: ['server.read'], dedicated: true, steps: ['Review findings'] }),
	feature({ id: 'smtp-restrictions', label: 'SMTP Restrictions', description: 'Prevent tenants from sending mail through unauthorized relays.', category: 'Security Center', icon: 'mail', layout: 'settings', path: '/tools/smtp-restrictions', capabilities: ['mail.write'], settingKey: 'smtp_restrictions', steps: ['Enable restriction', 'Save'], fields: [{ name: 'restrict', label: 'Restrict outbound SMTP to Postfix', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'two-factor', label: 'Two-Factor Authentication', description: 'Require TOTP for Director administrators.', category: 'Security Center', icon: 'lock', layout: 'settings', path: '/tools/two-factor', capabilities: ['server.settings.write'], settingKey: 'two_factor', steps: ['Enable policy', 'Save'], fields: [{ name: 'required', label: 'Require TOTP for server administrators', type: 'checkbox' }] }),
	feature({ id: 'security', label: 'Security & Host Configuration', description: 'Firewall review/apply and typed host reboot.', category: 'Security Center', icon: 'shield', layout: 'confirm', path: '/security', capabilities: ['server.read'], dedicated: true, steps: ['Review firewall', 'Apply or reboot'] }),
	feature({ id: 'audit', label: 'Audit Trail', description: 'Search privileged actions and before/after state.', category: 'Security Center', icon: 'audit', layout: 'table', path: '/audit', capabilities: ['security.audit.read'], dedicated: true, steps: ['Filter', 'Inspect'] }),
	feature({ id: 'wheel-group', label: 'Manage Wheel Group Users', description: 'Users allowed to use sudo on this host.', category: 'Security Center', icon: 'users', layout: 'settings', path: '/tools/wheel-group', capabilities: ['server.settings.write'], settingKey: 'wheel_group', steps: ['Edit members', 'Save'], fields: [{ name: 'members', label: 'Usernames', type: 'textarea' }] }),
	feature({ id: 'ssh-keys-root', label: "Manage root's SSH Keys", description: 'Store authorized public keys for host administration.', category: 'Security Center', icon: 'key', layout: 'settings', path: '/tools/ssh-keys-root', capabilities: ['server.settings.write'], settingKey: 'root_ssh_keys', steps: ['Paste keys', 'Save'], fields: [{ name: 'keys', label: 'Authorized public keys', type: 'textarea' }] }),

	feature({ id: 'basic-setup', label: 'Basic WebHost Manager Setup', description: 'Contact email, default nameservers, and the ethernet device used for new IPs.', category: 'Server Configuration', icon: 'edit', layout: 'wizard', path: '/tools/basic-setup', capabilities: ['server.settings.write'], settingKey: 'basic_setup', steps: ['Contact', 'Nameservers', 'Network', 'Review'], fields: [{ name: 'contact_email', label: 'Contact email', type: 'text', required: true }, { name: 'ns1', label: 'Nameserver 1', type: 'text' }, { name: 'ns2', label: 'Nameserver 2', type: 'text' }, { name: 'ethernet', label: 'Ethernet device', type: 'text', defaultValue: 'eth0' }] }),
	feature({ id: 'change-root-password', label: 'Change Root Password', description: 'Set the Ubuntu root password through the typed agent. Director sends it once and never stores it.', category: 'Server Configuration', icon: 'key', layout: 'status', path: '/tools/change-root-password', capabilities: ['server.settings.write'], steps: ['Enter the new password', 'Apply on the host'] }),
	feature({ id: 'server-profile', label: 'Server Profile', description: 'Standard, mail-only, or DNS-only profile that hides unused services.', category: 'Server Configuration', icon: 'box', layout: 'settings', path: '/tools/server-profile', capabilities: ['server.settings.write'], settingKey: 'server_profile', steps: ['Choose profile', 'Save'], fields: [{ name: 'profile', label: 'Profile', type: 'select', options: [{ value: 'standard', label: 'Standard hosting' }, { value: 'mail', label: 'Mail' }, { value: 'dns', label: 'DNS' }], defaultValue: 'standard' }] }),
	feature({ id: 'tweak-settings', label: 'Tweak Settings', description: 'Mail, domain, and notification defaults that apply host-wide.', category: 'Server Configuration', icon: 'edit', layout: 'settings', path: '/tools/tweak-settings', capabilities: ['server.settings.write'], settingKey: 'tweak_settings', steps: ['Edit defaults', 'Save'], fields: [{ name: 'max_emails_hour', label: 'Max emails per hour / domain', type: 'number', defaultValue: '500' }, { name: 'allow_parked', label: 'Allow parked domains', type: 'checkbox', defaultValue: 'on' }, { name: 'notify_disk', label: 'Notify at disk percent', type: 'number', defaultValue: '90' }, { name: 'default_php', label: 'Default PHP version', type: 'select', options: [{ value: '8.3', label: '8.3' }, { value: '8.4', label: '8.4' }, { value: '8.2', label: '8.2' }], defaultValue: '8.3' }] }),
	feature({ id: 'update-preferences', label: 'Update Preferences', description: 'Release channel and automatic install policy.', category: 'Server Configuration', icon: 'box', layout: 'form', path: '/updates', capabilities: ['server.read'], dedicated: true, steps: ['Review channel', 'Save'] }),
	feature({ id: 'configure-cron', label: 'Configure Host Cron Jobs', description: 'Schedules for backup, update check, and usage collection.', category: 'Server Configuration', icon: 'jobs', layout: 'settings', path: '/tools/configure-cron', capabilities: ['server.settings.write'], settingKey: 'host_cron', steps: ['Edit schedules', 'Save'], fields: [{ name: 'backup', label: 'Backup schedule', type: 'text', defaultValue: '0 2 * * *' }, { name: 'updates', label: 'Update check schedule', type: 'text', defaultValue: '0 4 * * *' }, { name: 'usage', label: 'Usage collection', type: 'text', defaultValue: '*/15 * * * *' }] }),
	feature({ id: 'initial-quota', label: 'Initial Quota Setup', description: 'Confirm disk-quota enforcement for tenant homes.', category: 'Server Configuration', icon: 'meter', layout: 'status', path: '/tools/initial-quota', capabilities: ['server.read'], steps: ['Review quota status'] }),
	feature({ id: 'link-nodes', label: 'Link Server Nodes', description: 'Attach additional compute or DNS nodes to this Director.', category: 'Server Configuration', icon: 'globe', layout: 'settings', path: '/tools/link-nodes', capabilities: ['server.settings.write'], settingKey: 'linked_nodes', steps: ['Add node URL', 'Save'], fields: [{ name: 'nodes', label: 'Node URLs', type: 'textarea' }] }),
	feature({ id: 'terminal', label: 'Terminal', description: 'Run audited host recipes: nginx test/reload and Postfix queue, flush, and status. This is not a freeform root shell.', category: 'Server Configuration', icon: 'jobs', layout: 'status', path: '/tools/terminal', capabilities: ['server.read'], steps: ['Choose a recipe', 'Review the agent output'] }),
	feature({ id: 'server-time', label: 'Server Time', description: 'Timezone used for cron, backups, and audit display.', category: 'Server Configuration', icon: 'pulse', layout: 'settings', path: '/tools/server-time', capabilities: ['server.settings.write'], settingKey: 'server_time', steps: ['Set timezone', 'Save'], fields: [{ name: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: true }] }),

	feature({ id: 'contact-manager', label: 'Contact Manager', description: 'Who receives disk, service, and update alerts.', category: 'Server Contacts', icon: 'mail', layout: 'settings', path: '/tools/contact-manager', capabilities: ['server.settings.write'], settingKey: 'contacts', steps: ['Add contacts', 'Save'], fields: [{ name: 'email', label: 'Alert email', type: 'text', required: true }, { name: 'notify_disk', label: 'Disk alerts', type: 'checkbox', defaultValue: 'on' }, { name: 'notify_services', label: 'Service alerts', type: 'checkbox', defaultValue: 'on' }, { name: 'notify_updates', label: 'Update alerts', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'system-mail-prefs', label: 'Edit System Mail Preferences', description: 'From-address and relay used for Director notifications.', category: 'Server Contacts', icon: 'mail', layout: 'settings', path: '/tools/system-mail-prefs', capabilities: ['server.settings.write'], settingKey: 'system_mail', steps: ['Edit addresses', 'Save'], fields: [{ name: 'from', label: 'From address', type: 'text' }, { name: 'relay', label: 'SMTP relay host', type: 'text' }] }),

	feature({ id: 'services', label: 'Service Status', description: 'Measured vitals, managed services, and control actions.', category: 'Server Status', icon: 'pulse', layout: 'status', path: '/status', capabilities: ['server.read'], dedicated: true, steps: ['Inspect', 'Control'] }),
	feature({ id: 'server-information', label: 'Server Information', description: 'Hostname, load, memory, disk, and uptime from the live host probe.', category: 'Server Status', icon: 'pulse', layout: 'status', path: '/status', capabilities: ['server.read'], dedicated: true, steps: ['Review vitals'] }),
	feature({ id: 'task-queue', label: 'Task Queue Monitor', description: 'Background jobs, retries, and cancellation.', category: 'Server Status', icon: 'jobs', layout: 'table', path: '/jobs', capabilities: ['server.read', 'accounts.read'], dedicated: true, steps: ['Filter', 'Inspect'] }),
	feature({ id: 'daily-process-log', label: 'Daily Process Log', description: 'Recent process snapshots collected with host telemetry.', category: 'Server Status', icon: 'pulse', layout: 'table', path: '/processes', capabilities: ['server.read'], dedicated: true, steps: ['Review snapshot'] }),

	feature({ id: 'service-manager', label: 'Service Manager', description: 'Enable monitoring and control for managed services.', category: 'Service Configuration', icon: 'pulse', layout: 'table', path: '/status', capabilities: ['server.read'], dedicated: true, steps: ['Review services'] }),
	feature({ id: 'nameserver-selection', label: 'Nameserver Selection', description: 'PowerDNS is the Kelmor nameserver. Record that choice and the listening address.', category: 'Service Configuration', icon: 'globe', layout: 'settings', path: '/tools/nameserver-selection', capabilities: ['server.settings.write'], settingKey: 'nameserver_selection', steps: ['Confirm', 'Save'], fields: [{ name: 'software', label: 'Nameserver', type: 'select', options: [{ value: 'pdns', label: 'PowerDNS' }, { value: 'disabled', label: 'Disabled' }], defaultValue: 'pdns' }] }),
	feature({ id: 'mailserver-config', label: 'Mailserver Configuration', description: 'IMAP/POP and submission ports for Dovecot and Postfix.', category: 'Service Configuration', icon: 'mail', layout: 'settings', path: '/tools/mailserver-config', capabilities: ['server.settings.write'], settingKey: 'mailserver', steps: ['Edit ports', 'Save'], fields: [{ name: 'imap', label: 'IMAP port', type: 'number', defaultValue: '993' }, { name: 'submission', label: 'Submission port', type: 'number', defaultValue: '587' }] }),
	feature({ id: 'ftp-server-config', label: 'FTP Server Configuration', description: 'vsftpd pasv range and banner.', category: 'Service Configuration', icon: 'files', layout: 'settings', path: '/tools/ftp-server-config', capabilities: ['server.settings.write'], settingKey: 'ftp_server', steps: ['Edit', 'Save'], fields: [{ name: 'pasv_min', label: 'PASV min port', type: 'number', defaultValue: '40000' }, { name: 'pasv_max', label: 'PASV max port', type: 'number', defaultValue: '40100' }] }),
	feature({ id: 'ftp-server-selection', label: 'FTP Server Selection', description: 'Enable or disable virtual FTP.', category: 'Service Configuration', icon: 'files', layout: 'settings', path: '/tools/ftp-server-selection', capabilities: ['server.settings.write'], settingKey: 'ftp_selection', steps: ['Choose', 'Save'], fields: [{ name: 'daemon', label: 'FTP daemon', type: 'select', options: [{ value: 'vsftpd', label: 'vsftpd' }, { value: 'disabled', label: 'Disabled' }], defaultValue: 'vsftpd' }] }),
	feature({ id: 'exim-config', label: 'Mail Configuration Manager', description: 'Postfix / rspamd policy that Kelmor applies instead of Exim.', category: 'Service Configuration', icon: 'mail', layout: 'settings', path: '/tools/exim-config', capabilities: ['server.settings.write'], settingKey: 'mail_config', steps: ['Edit policy', 'Save'], fields: [{ name: 'require_auth', label: 'Require auth on submission', type: 'checkbox', defaultValue: 'on' }, { name: 'milter', label: 'Enable rspamd milter', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'directory-index', label: 'DirectoryIndex Priority', description: 'Filenames nginx/php-fpm treat as index pages.', category: 'Service Configuration', icon: 'files', layout: 'settings', path: '/tools/directory-index', capabilities: ['server.settings.write'], settingKey: 'directory_index', steps: ['Edit list', 'Save'], fields: [{ name: 'indexes', label: 'Index filenames', type: 'text', defaultValue: 'index.php index.html' }] }),
	feature({ id: 'log-rotation', label: 'Log Rotation Configuration', description: 'Retention for nginx, mail, and panel logs.', category: 'Service Configuration', icon: 'files', layout: 'settings', path: '/tools/log-rotation', capabilities: ['server.settings.write'], settingKey: 'log_rotation', steps: ['Set days', 'Save'], fields: [{ name: 'days', label: 'Retain days', type: 'number', defaultValue: '14' }] }),
	feature({ id: 'service-ssl', label: 'Manage Service SSL Certificates', description: 'Host and account TLS material managed on the SSL / TLS page.', category: 'Service Configuration', icon: 'lock', layout: 'table', path: '/ssl?task=service', capabilities: ['websites.read'], dedicated: true, steps: ['Review service certificates'] }),

	feature({ id: 'websites', label: 'MultiPHP Manager', description: 'Website runtimes and PHP versions.', category: 'Software', icon: 'code', layout: 'table', path: '/websites', capabilities: ['accounts.read', 'websites.read'], matchAll: true, dedicated: true, steps: ['Select site', 'Change PHP'] }),
	feature({ id: 'multiphp-ini', label: 'MultiPHP INI Editor', description: 'Default php.ini overrides applied to new pools.', category: 'Software', icon: 'code', layout: 'settings', path: '/tools/multiphp-ini', capabilities: ['websites.write'], settingKey: 'php_ini', steps: ['Edit directives', 'Save'], fields: [{ name: 'memory_limit', label: 'memory_limit', type: 'text', defaultValue: '256M' }, { name: 'upload_max_filesize', label: 'upload_max_filesize', type: 'text', defaultValue: '64M' }, { name: 'max_execution_time', label: 'max_execution_time', type: 'number', defaultValue: '60' }] }),
	feature({ id: 'nginx-manager', label: 'NGINX Manager', description: 'Default vhost caching and HTTPS redirect policy.', category: 'Software', icon: 'globe', layout: 'settings', path: '/tools/nginx-manager', capabilities: ['server.settings.write'], settingKey: 'nginx_manager', steps: ['Edit policy', 'Save'], fields: [{ name: 'https_redirect', label: 'Force HTTPS', type: 'checkbox', defaultValue: 'on' }, { name: 'gzip', label: 'Enable gzip', type: 'checkbox', defaultValue: 'on' }] }),
	feature({ id: 'wp-toolkit', label: 'WP Toolkit', description: 'Install WordPress into an account document root through the existing API.', category: 'Software', icon: 'box', layout: 'account-action', path: '/tools/wp-toolkit', capabilities: ['websites.write', 'applications.write'], steps: ['Select account', 'Choose site', 'Queue install'], fields: [accountSelect, { name: 'website_id', label: 'Website', type: 'text', required: true, help: 'Website id from MultiPHP Manager.' }, { name: 'title', label: 'Site title', type: 'text', defaultValue: 'WordPress' }, { name: 'admin_user', label: 'Admin user', type: 'text', required: true }, { name: 'admin_password', label: 'Admin password', type: 'password', required: true }, { name: 'admin_email', label: 'Admin email', type: 'text', required: true }], related: ['websites'] }),

	feature({ id: 'sql', label: 'Database Manager', description: 'MariaDB, MySQL, and PostgreSQL databases.', category: 'SQL Services', icon: 'database', layout: 'table', path: '/sql', capabilities: ['accounts.read', 'databases.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Create or delete'] }),
	feature({ id: 'mysql-root-password', label: 'Change Database Root Password', description: 'Rotate the MariaDB root password through the typed agent. Director does not persist it. This is a server-scope operation.', category: 'SQL Services', icon: 'key', layout: 'status', path: '/tools/mysql-root-password', capabilities: ['server.settings.write'], steps: ['Enter the new password', 'Apply on the host'], related: ['sql'] }),
	feature({ id: 'db-user-password', label: 'Change Database User Password', description: 'Rotate the auto-provisioned database user for an account.', category: 'SQL Services', icon: 'key', layout: 'account-action', path: '/sql', capabilities: ['databases.write'], dedicated: true, steps: ['Open Database Manager'] }),
	feature({ id: 'additional-mysql-hosts', label: 'Additional MySQL Access Hosts', description: 'Remote hosts allowed to reach MariaDB for an account.', category: 'SQL Services', icon: 'database', layout: 'settings', path: '/tools/additional-mysql-hosts', capabilities: ['databases.write'], settingKey: 'mysql_hosts', steps: ['Enter hosts', 'Save'], fields: [{ name: 'hosts', label: 'Allowed hosts', type: 'textarea', defaultValue: '127.0.0.1' }] }),
	feature({ id: 'postgres-config', label: 'Configure PostgreSQL', description: 'Listening address and auth method for the control-plane database.', category: 'SQL Services', icon: 'database', layout: 'settings', path: '/tools/postgres-config', capabilities: ['server.settings.write'], settingKey: 'postgres', steps: ['Edit', 'Save'], fields: [{ name: 'listen', label: 'Listen address', type: 'text', defaultValue: '127.0.0.1' }] }),
	feature({ id: 'show-mysql-processes', label: 'Show MySQL Processes', description: 'Open Database Manager connection details; process lists stay on the SQL host.', category: 'SQL Services', icon: 'database', layout: 'table', path: '/sql', capabilities: ['databases.read'], dedicated: true, steps: ['Open manager'] }),

	feature({ id: 'processes', label: 'Process Manager', description: 'Inspect the live /proc snapshot and send typed TERM or KILL signals to unprotected processes.', category: 'System Health', icon: 'pulse', layout: 'table', path: '/processes', capabilities: ['server.read'], dedicated: true, steps: ['Review snapshot', 'Signal leftover processes'] }),
	feature({ id: 'background-killer', label: 'Background Process Killer', description: 'Processes Kelmor should terminate when found under tenant UIDs.', category: 'System Health', icon: 'pulse', layout: 'settings', path: '/tools/background-killer', capabilities: ['server.settings.write'], settingKey: 'process_killer', steps: ['List binaries', 'Save'], fields: [{ name: 'binaries', label: 'Binary names', type: 'textarea', defaultValue: 'ircd\nbitchx' }] }),
	feature({ id: 'disk-usage', label: 'Show Current Disk Usage', description: 'Host and account disk observations.', category: 'System Health', icon: 'meter', layout: 'status', path: '/usage', capabilities: ['billing.usage.read'], dedicated: true, steps: ['Review usage'] }),

	feature({ id: 'graceful-reboot', label: 'Graceful Server Reboot', description: 'Typed REBOOT confirmation that drains services first.', category: 'System Reboot', icon: 'pulse', layout: 'confirm', path: '/security', capabilities: ['server.read'], dedicated: true, steps: ['Type REBOOT', 'Confirm'] }),
	feature({ id: 'forceful-reboot', label: 'Forceful Server Reboot', description: 'Same typed reboot path. Kelmor always goes through the privileged agent.', category: 'System Reboot', icon: 'pulse', layout: 'confirm', path: '/security', capabilities: ['server.read'], dedicated: true, steps: ['Type REBOOT', 'Confirm'] }),

	feature({ id: 'file-manager', label: 'File Manager', description: 'Browse and edit account files.', category: 'Files', icon: 'files', layout: 'table', path: '/files', capabilities: ['accounts.read', 'files.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Browse'] }),
	feature({ id: 'ftp', label: 'FTP Accounts', description: 'Virtual FTP users chrooted to account content.', category: 'Files', icon: 'files', layout: 'table', path: '/ftp', capabilities: ['accounts.read', 'files.read'], matchAll: true, dedicated: true, steps: ['Select account', 'Create user'] }),

	feature({ id: 'ssl', label: 'SSL / TLS', description: 'Certificate inventory and AutoSSL requests.', category: 'SSL/TLS', icon: 'lock', layout: 'table', path: '/ssl', capabilities: ['accounts.read', 'websites.read'], matchAll: true, dedicated: true, steps: ['Review', 'Request'] }),
	feature({ id: 'generate-csr', label: 'Generate an SSL Certificate and Signing Request', description: 'Request an account certificate for a hostname through AutoSSL.', category: 'SSL/TLS', icon: 'lock', layout: 'form', path: '/ssl?task=request', capabilities: ['websites.write'], dedicated: true, steps: ['Enter hostname', 'Queue'] }),

	feature({ id: 'jobs', label: 'Jobs', description: 'Inspect and retry background operations.', category: 'System Tools', icon: 'jobs', layout: 'table', path: '/jobs', capabilities: ['server.read', 'accounts.read'], dedicated: true, steps: ['Filter', 'Retry'] }),
	feature({ id: 'updates', label: 'Software Updates', description: 'Check, install, and schedule verified Kelmor releases.', category: 'System Tools', icon: 'box', layout: 'status', path: '/updates', capabilities: ['server.read'], dedicated: true, steps: ['Check', 'Install'] }),
	feature({ id: 'theme-manager', label: 'Theme Manager', description: 'Director chrome density and favorite tools on Home.', category: 'Themes', icon: 'edit', layout: 'settings', path: '/tools/theme-manager', capabilities: ['server.settings.write'], settingKey: 'theme', steps: ['Choose density', 'Save'], fields: [{ name: 'density', label: 'Density', type: 'select', options: [{ value: 'comfortable', label: 'Comfortable' }, { value: 'compact', label: 'Compact' }], defaultValue: 'comfortable' }] }),
	feature({ id: 'locales', label: 'Configure Application Locales', description: 'Display locale for dates and numbers in Director.', category: 'Locales', icon: 'globe', layout: 'settings', path: '/tools/locales', capabilities: ['server.settings.write'], settingKey: 'locale', steps: ['Choose locale', 'Save'], fields: [{ name: 'locale', label: 'Locale', type: 'text', defaultValue: 'en-US' }] }),
	feature({ id: 'api-tokens-whm', label: 'Manage API Tokens', description: 'Account-safe API tokens from account services.', category: 'Development', icon: 'key', layout: 'table', path: '/accounts', capabilities: ['api_tokens.read'], dedicated: true, steps: ['Open account services'] }),
	feature({ id: 'api-shell', label: 'API Shell', description: 'OpenAPI HTML for the Kelmor control API.', category: 'Development', icon: 'code', layout: 'status', path: '/tools/api-shell', capabilities: ['server.read'], steps: ['Open /openapi on the API'] }),
	feature({ id: 'support-center', label: 'Support Center', description: 'How to collect logs, jobs, and audit events for a support case.', category: 'Support', icon: 'audit', layout: 'status', path: '/tools/support-center', capabilities: ['server.read'], steps: ['Copy host facts'] }),
	feature({ id: 'multi-modify', label: 'Modify/Upgrade Multiple Accounts', description: 'Apply one package to many accounts after review.', category: 'Multi Account Functions', icon: 'box', layout: 'settings', path: '/tools/multi-modify', capabilities: ['accounts.modify'], settingKey: 'multi_modify', steps: ['List usernames', 'Choose package', 'Save plan'], fields: [{ name: 'usernames', label: 'Usernames', type: 'textarea', required: true }, packageSelect] }),
	feature({ id: 'multi-ip', label: "Change Multiple Sites' IP Addresses", description: 'Assign one IP to many accounts.', category: 'Multi Account Functions', icon: 'globe', layout: 'settings', path: '/tools/multi-ip', capabilities: ['accounts.modify'], settingKey: 'multi_ip', steps: ['List usernames', 'Enter IP', 'Save plan'], fields: [{ name: 'usernames', label: 'Usernames', type: 'textarea', required: true }, { name: 'ip_address', label: 'IP address', type: 'text', required: true }] }),

	feature({ id: 'feature-showcase', label: 'Feature Showcase', description: 'New Director capabilities grouped by release. Nothing is hidden for missing privileges.', category: 'cPanel', icon: 'box', layout: 'status', path: '/tools/feature-showcase', capabilities: ['server.read'], steps: ['Review new tools'] }),
	feature({ id: 'change-log', label: 'Change Log', description: 'Operator-facing notes for this host’s Kelmor release channel.', category: 'cPanel', icon: 'audit', layout: 'status', path: '/updates', capabilities: ['server.read'], dedicated: true, steps: ['Open Software Updates'] }),
	feature({ id: 'web-template-editor', label: 'Web Template Editor', description: 'Default index and error pages copied into new account document roots.', category: 'cPanel', icon: 'files', layout: 'settings', path: '/tools/web-template-editor', capabilities: ['server.settings.write'], settingKey: 'web_templates', steps: ['Edit templates', 'Save'], fields: [{ name: 'index_html', label: 'Default index.html', type: 'textarea' }, { name: 'error_html', label: 'Default error page', type: 'textarea' }], related: ['skeleton-directory'] }),
	feature({ id: 'convert-addon', label: 'Convert Addon Domain to Account', description: 'Promote an addon domain into its own POSIX account after review.', category: 'cPanel', icon: 'plus', layout: 'wizard', path: '/tools/convert-addon', capabilities: ['accounts.create', 'domains.write'], matchAll: true, steps: ['Select source account', 'Choose addon domain', 'Review new identity', 'Queue'], fields: [accountSelect, { name: 'addon_domain', label: 'Addon domain', type: 'text', required: true }, { name: 'username', label: 'New username', type: 'text', required: true }, packageSelect], related: ['create-account', 'list-domains'] }),
	feature({ id: 'easyapache', label: 'EasyApache / Runtime Builder', description: 'Install php-fpm 8.3, 8.4, or 8.5 through the typed agent. MultiPHP Manager then assigns a version to each site.', category: 'Software', icon: 'code', layout: 'status', path: '/tools/easyapache', capabilities: ['server.settings.write'], steps: ['Review installed runtimes', 'Install a missing version'], related: ['websites', 'multiphp-ini'] }),
	feature({ id: 'module-installers', label: 'Module Installers', description: 'Record PECL, PEAR, Perl, and Ruby modules the host should present to tenants.', category: 'Software', icon: 'box', layout: 'settings', path: '/tools/module-installers', capabilities: ['server.settings.write'], settingKey: 'module_installers', steps: ['List modules', 'Save'], fields: [{ name: 'pecl', label: 'PHP PECL modules', type: 'textarea' }, { name: 'pear', label: 'PHP PEAR modules', type: 'textarea' }, { name: 'perl', label: 'Perl modules', type: 'textarea' }, { name: 'ruby', label: 'Ruby gems', type: 'textarea' }] }),
	feature({ id: 'perl-modules', label: 'Install a Perl Module', description: 'Queue a Perl module name for host installation review.', category: 'Software', icon: 'code', layout: 'form', path: '/tools/perl-modules', capabilities: ['server.settings.write'], settingKey: 'perl_modules', steps: ['Name the module', 'Save'], fields: [{ name: 'module', label: 'Perl module', type: 'text', required: true }] }),
	feature({ id: 'php-pear', label: 'Install a PHP PEAR Module', description: 'Queue a PEAR package name for host installation review.', category: 'Software', icon: 'code', layout: 'form', path: '/tools/php-pear', capabilities: ['server.settings.write'], settingKey: 'php_pear', steps: ['Name the package', 'Save'], fields: [{ name: 'package', label: 'PEAR package', type: 'text', required: true }] }),
	feature({ id: 'php-pecl', label: 'Install a PHP PECL Module', description: 'Queue a PECL extension name for host installation review.', category: 'Software', icon: 'code', layout: 'form', path: '/tools/php-pecl', capabilities: ['server.settings.write'], settingKey: 'php_pecl', steps: ['Name the extension', 'Save'], fields: [{ name: 'extension', label: 'PECL extension', type: 'text', required: true }] }),
	feature({ id: 'ruby-gems', label: 'Install a Ruby Gem', description: 'Queue a Ruby gem name for host installation review.', category: 'Software', icon: 'box', layout: 'form', path: '/tools/ruby-gems', capabilities: ['server.settings.write'], settingKey: 'ruby_gems', steps: ['Name the gem', 'Save'], fields: [{ name: 'gem', label: 'Gem name', type: 'text', required: true }] }),
	feature({ id: 'rebuild-rpm', label: 'Rebuild RPM Database', description: 'Kelmor uses apt on Ubuntu. This page records a package-index refresh request.', category: 'Software', icon: 'box', layout: 'confirm', path: '/tools/rebuild-rpm', capabilities: ['server.settings.write'], steps: ['Review', 'Request apt update'] }),
	feature({ id: 'mysql-upgrade', label: 'MySQL/MariaDB Upgrade', description: 'Plan a MariaDB major-version upgrade. The typed agent applies it; Director stores the target version.', category: 'SQL Services', icon: 'database', layout: 'settings', path: '/tools/mysql-upgrade', capabilities: ['server.settings.write'], settingKey: 'mariadb_upgrade', steps: ['Choose version', 'Save plan'], fields: [{ name: 'target', label: 'Target MariaDB version', type: 'select', options: [{ value: '10.11', label: '10.11' }, { value: '11.4', label: '11.4' }], defaultValue: '10.11' }] }),
	feature({ id: 'phpmyadmin', label: 'phpMyAdmin', description: 'Publish the host phpMyAdmin package on phpmyadmin.<domain> and open it for the selected account.', category: 'SQL Services', icon: 'database', layout: 'status', path: '/tools/phpmyadmin', capabilities: ['databases.read'], steps: ['Select account', 'Publish and open'], related: ['sql'] }),
	feature({ id: 'manage-autossl', label: 'Manage AutoSSL', description: 'Request and renew account certificates through ACME on the SSL / TLS manager.', category: 'SSL/TLS', icon: 'lock', layout: 'form', path: '/ssl?task=autossl', capabilities: ['websites.write'], dedicated: true, steps: ['Choose hostname', 'Queue AutoSSL'] }),
	feature({ id: 'install-ssl', label: 'Install an SSL Certificate on a Domain', description: 'Request a certificate for a hostname on the SSL / TLS manager.', category: 'SSL/TLS', icon: 'lock', layout: 'form', path: '/ssl?task=request', capabilities: ['websites.write'], dedicated: true, steps: ['Select hostname', 'Queue'] }),
	feature({ id: 'ssl-storage', label: 'SSL Storage Manager', description: 'Certificate inventory already issued for accounts on this host.', category: 'SSL/TLS', icon: 'lock', layout: 'table', path: '/ssl?task=inventory', capabilities: ['websites.read'], dedicated: true, steps: ['Review inventory'] }),
	feature({ id: 'ssl-tls-status', label: 'SSL/TLS Status', description: 'Which sites currently present a valid certificate.', category: 'SSL/TLS', icon: 'lock', layout: 'table', path: '/ssl?task=status', capabilities: ['websites.read'], dedicated: true, steps: ['Review status'] }),
	feature({ id: 'apache-status', label: 'HTTP Server Status', description: 'nginx worker and connection observations from Service Status.', category: 'Server Status', icon: 'pulse', layout: 'status', path: '/status', capabilities: ['server.read'], dedicated: true, steps: ['Open Service Status'] }),
	feature({ id: 'apache-configuration', label: 'HTTP Server Configuration', description: 'nginx defaults that Kelmor writes for new vhosts.', category: 'Service Configuration', icon: 'globe', layout: 'settings', path: '/tools/apache-configuration', capabilities: ['server.settings.write'], settingKey: 'http_server', steps: ['Edit defaults', 'Save'], fields: [{ name: 'client_max_body_size', label: 'client_max_body_size', type: 'text', defaultValue: '64m' }, { name: 'keepalive_timeout', label: 'keepalive_timeout', type: 'number', defaultValue: '65' }], related: ['nginx-manager'] }),
	feature({ id: 'statistics-software', label: 'Statistics Software Configuration', description: 'Whether Director should collect per-account bandwidth and disk on the usage interval.', category: 'Service Configuration', icon: 'chart', layout: 'settings', path: '/tools/statistics-software', capabilities: ['server.settings.write'], settingKey: 'statistics', steps: ['Enable collection', 'Save'], fields: [{ name: 'collect_bandwidth', label: 'Collect bandwidth', type: 'checkbox', defaultValue: 'on' }, { name: 'collect_disk', label: 'Collect disk', type: 'checkbox', defaultValue: 'on' }], related: ['usage'] }),
	feature({ id: 'synchronize-dns', label: 'Synchronize DNS Records', description: 'Re-publish every managed zone from the control plane to PowerDNS.', category: 'DNS Functions', icon: 'globe', layout: 'confirm', path: '/tools/synchronize-dns', capabilities: ['dns.write'], steps: ['Review', 'Queue sync'], related: ['dns'] }),
	feature({ id: 'nameserver-ips', label: 'Nameserver IPs', description: 'Public addresses advertised for ns1/ns2.', category: 'Networking Setup', icon: 'globe', layout: 'settings', path: '/tools/nameserver-ips', capabilities: ['server.settings.write'], settingKey: 'nameserver_ips', steps: ['Enter addresses', 'Save'], fields: [{ name: 'ns1_ip', label: 'ns1 IPv4', type: 'text' }, { name: 'ns2_ip', label: 'ns2 IPv4', type: 'text' }], related: ['change-hostname'] }),
	feature({ id: 'delete-ip', label: 'Show and Delete Reserved IPs', description: 'Remove an address from the assignable pool.', category: 'IP Functions', icon: 'globe', layout: 'settings', path: '/tools/delete-ip', capabilities: ['server.settings.write'], settingKey: 'ip_pool_removed', steps: ['Enter address', 'Save removal'], fields: [{ name: 'address', label: 'IP address', type: 'text', required: true }], related: ['add-ip', 'rebuild-ip-pool'] }),
	feature({ id: 'park-domain', label: 'Park a Domain', description: 'Add an alias/parked domain on an account.', category: 'DNS Functions', icon: 'globe', layout: 'table', path: '/domains?view=alias', capabilities: ['domains.write'], dedicated: true, steps: ['Select account', 'Add alias'] }),
	feature({ id: 'edit-dns-zone', label: 'Edit DNS Zone', description: 'Open DNS Zone Manager for an account.', category: 'DNS Functions', icon: 'edit', layout: 'table', path: '/dns', capabilities: ['dns.write'], dedicated: true, steps: ['Select zone', 'Edit records'] }),
	feature({ id: 'copy-account', label: 'Copy an Account from Another Server', description: 'Native transfer and extracted-archive import.', category: 'Transfers', icon: 'transfer', layout: 'wizard', path: '/transfers', capabilities: ['accounts.create'], dedicated: true, steps: ['Choose source', 'Review', 'Queue'] }),
	feature({ id: 'review-transfers', label: 'Review Transfers and Restores', description: 'Open Jobs filtered to transfer and restore operations.', category: 'Transfers', icon: 'jobs', layout: 'table', path: '/jobs?q=transfer', capabilities: ['accounts.read'], dedicated: true, steps: ['Filter transfer jobs'] }),
	feature({ id: 'mailman', label: 'Mailing Lists', description: 'Create multi-member Postfix lists and edit membership from Email Management.', category: 'Email', icon: 'mail', layout: 'table', path: '/email?tab=lists', capabilities: ['mail.read'], dedicated: true, steps: ['Select account', 'Create or edit lists'], related: ['email'] }),
	feature({ id: 'track-delivery', label: 'Track Delivery', description: 'Filter mail jobs and audit events for a recipient.', category: 'Email', icon: 'mail', layout: 'table', path: '/jobs?q=mail', capabilities: ['mail.read'], dedicated: true, steps: ['Filter mail jobs'] }),
	feature({ id: 'view-relayers', label: 'View Relayers', description: 'Accounts allowed to relay through this host’s Postfix.', category: 'Email', icon: 'mail', layout: 'settings', path: '/tools/view-relayers', capabilities: ['mail.write'], settingKey: 'relayers', steps: ['Edit list', 'Save'], fields: [{ name: 'usernames', label: 'Relay usernames', type: 'textarea' }] }),
	feature({ id: 'mail-troubleshooter', label: 'Mail Troubleshooter', description: 'Checklist for deferred Postfix mail: queue policy, DNS, and deliverability.', category: 'Email', icon: 'mail', layout: 'status', path: '/tools/mail-troubleshooter', capabilities: ['mail.read'], steps: ['Review checklist'], related: ['mail-queue', 'deliverability'] }),
	feature({ id: 'configure-email-client', label: 'Configure an Email Client', description: 'IMAP and submission settings already shown in Webmail.', category: 'Email', icon: 'webmail', layout: 'status', path: '/webmail', capabilities: ['mail.read'], dedicated: true, steps: ['Copy connection settings'] }),
	feature({ id: 'customization', label: 'Customization', description: 'Logo text and footer note on Director chrome.', category: 'Themes', icon: 'edit', layout: 'settings', path: '/tools/customization', capabilities: ['server.settings.write'], settingKey: 'customization', steps: ['Edit chrome', 'Save'], fields: [{ name: 'product_name', label: 'Product name', type: 'text', defaultValue: 'Kelmor Director' }, { name: 'footer', label: 'Footer note', type: 'text' }], related: ['theme-manager'] }),
	feature({ id: 'plugins', label: 'Manage Plugins', description: 'Host packages Kelmor already wires, such as rspamd. Enable or review their install state on this host.', category: 'Plugins', icon: 'box', layout: 'status', path: '/tools/plugins', capabilities: ['server.read'], steps: ['Review host apps'] }),
	feature({ id: 'market', label: 'Market', description: 'Install first-party host apps: phpMyAdmin, Roundcube, and WordPress through the typed agent.', category: 'Market', icon: 'box', layout: 'status', path: '/tools/market', capabilities: ['server.read'], steps: ['Select an account', 'Enable an app'], related: ['packages', 'features', 'phpmyadmin'] }),
	feature({ id: 'grant-support-access', label: 'Grant Support Access', description: 'Issue a time-limited Director session note for a support engineer. Store the ticket id only.', category: 'Support', icon: 'key', layout: 'settings', path: '/tools/grant-support-access', capabilities: ['server.settings.write'], settingKey: 'support_access', steps: ['Enter ticket', 'Save'], fields: [{ name: 'ticket', label: 'Ticket id', type: 'text', required: true }, { name: 'hours', label: 'Hours valid', type: 'number', defaultValue: '24' }] }),
	feature({ id: 'diagnostics-log', label: 'Download a Diagnostics File', description: 'How to collect jobs, audit events, and host logs for a support case.', category: 'Support', icon: 'files', layout: 'status', path: '/tools/diagnostics-log', capabilities: ['server.read'], steps: ['Copy collection steps'], related: ['jobs', 'audit'] }),
	feature({ id: 'reset-mailman', label: 'Reset a Mailing List Password', description: 'Edit mailing-list members or rotate a mailbox password from Email Management. Lists are Postfix aliases, not GNU Mailman.', category: 'cPanel', icon: 'key', layout: 'table', path: '/email?tab=lists', capabilities: ['mail.write'], dedicated: true, steps: ['Open mailing lists'], related: ['email'] }),
]

export function featureById (id: string): WhmFeature | undefined {
	return whmFeatures.find((entry) => entry.id === id)
}

export function featureByPath (pathname: string, search = ''): WhmFeature | undefined {
	const path = `${pathname}${search}`
	return whmFeatures.find((entry) => entry.path === path) || whmFeatures.find((entry) => entry.path === pathname)
}

export function toToolDefinition (feature: WhmFeature): ToolDefinition {
	return {
		id: feature.id,
		label: feature.label,
		description: feature.description,
		category: feature.category,
		path: feature.path,
		icon: feature.icon,
		capabilities: feature.capabilities,
		matchAll: feature.matchAll,
	}
}
